# Generated by Django 2.2.5 on 2019-11-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191129_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='check',
            new_name='value',
        ),
    ]
